<?php

// Exit if accessed directly
if ( !defined('ABSPATH')) exit;

/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */
// require ( get_template_directory() . '/includes/functions.php' );
// require ( get_template_directory() . '/includes/theme-options/theme-options.php' );
require_once( dirname( __FILE__ ) . '/inc/init.php' );
?>